In [1]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression


In [4]:
import numpy as np

def bam(input_pairs, output_pairs):
    """
    Implements a Bidirectional Associative Memory (BAM).

    Args:
        input_pairs (list): A list of input vector pairs.
        output_pairs (list): A list of output vector pairs.

    Returns:
        numpy.ndarray: The weight matrix of the BAM.
    """
    # Ensure that the number of input and output pairs is the same
    assert len(input_pairs) == len(output_pairs)

    # Get the number of input and output vector pairs
    num_pairs = len(input_pairs)

    # Initialize the weight matrix
    weight_matrix = np.zeros((len(input_pairs[0]), len(output_pairs[0])))

    # Compute the weight matrix
    for i in range(num_pairs):
        input_vector = np.array(input_pairs[i])
        output_vector = np.array(output_pairs[i])
        weight_matrix += np.outer(input_vector, output_vector)

    return weight_matrix

# Example usage
input_pairs = [
    [1, 0, 1, 0],
    [0, 1, 0, 1]
]

output_pairs = [
    [1, 0, 1],
    [0, 1, 0]
]

weight_matrix = bam(input_pairs, output_pairs)
print("Weight Matrix:\n", weight_matrix)

Weight Matrix:
 [[1. 0. 1.]
 [0. 1. 0.]
 [1. 0. 1.]
 [0. 1. 0.]]


In [7]:
# Import Python Libraries
import numpy as np

# Take two sets of patterns:
# Set A: Input Pattern
x1 = np.array([1, 1, 1, 1, 1, 1]).reshape(6, 1)
x2 = np.array([-1, -1, -1, -1, -1, -1]).reshape(6, 1)
x3 = np.array([1, 1, -1, -1, 1, 1]).reshape(6, 1)
x4 = np.array([-1, -1, 1, 1, -1, -1]).reshape(6, 1)

# Set B: Target Pattern
y1 = np.array([1, 1, 1]).reshape(3, 1)
y2 = np.array([-1, -1, -1]).reshape(3, 1)
y3 = np.array([1, -1, 1]).reshape(3, 1)
y4 = np.array([-1, 1, -1]).reshape(3, 1)

'''
print("Set A: Input Pattern, Set B: Target Pattern")
print("\nThe input for pattern 1 is")
print(x1)
print("\nThe target for pattern 1 is")
print(y1)
print("\nThe input for pattern 2 is")
print(x2)
print("\nThe target for pattern 2 is")
print(y2)
print("\nThe input for pattern 3 is")
print(x3)
print("\nThe target for pattern 3 is")
print(y3)
print("\nThe input for pattern 4 is")
print(x4)
print("\nThe target for pattern 4 is")
print(y4)

print("\n------------------------------")
'''
# Calculate weight Matrix: W
inputSet = np.concatenate((x1, x2, x3, x4), axis = 1)
targetSet = np.concatenate((y1.T, y2.T, y3.T, y4.T), axis = 0)
print("\nWeight matrix:")
weight = np.dot(inputSet, targetSet)
print(weight)

print("\n------------------------------")

# Testing Phase
# Test for Input Patterns: Set A
print("\nTesting for input patterns: Set A")
def testInputs(x, weight):
# Multiply the input pattern with the weight matrix
# (weight.T X x)
    y = np.dot(weight.T, x)
    y[y < 0] = -1
    y[y >= 0] = 1
    return np.array(y)

print("\nOutput of input pattern 1") 
print(testInputs(x1, weight))
print("\nOutput of input pattern 2")
print(testInputs(x2, weight))
print("\nOutput of input pattern 3")
print(testInputs(x3, weight))
print("\nOutput of input pattern 4")
print(testInputs(x4, weight))

# Test for Target Patterns: Set B
print("\nTesting for target patterns: Set B")
def testTargets(y, weight):
    # Multiply the target pattern with the weight matrix
    # (weight X y)
    x = np.dot(weight, y)
    x[x <= 0] = -1
    x[x > 0] = 1
    return np.array(x)

print("\nOutput of target pattern 1")
print(testTargets(y1, weight))
print("\nOutput of target pattern 2")
print(testTargets(y2, weight))
print("\nOutput of target pattern 3")
print(testTargets(y3, weight))
print("\nOutput of target pattern 4")
print(testTargets(y4, weight))



Weight matrix:
[[4 0 4]
 [4 0 4]
 [0 4 0]
 [0 4 0]
 [4 0 4]
 [4 0 4]]

------------------------------

Testing for input patterns: Set A

Output of input pattern 1
[[1]
 [1]
 [1]]

Output of input pattern 2
[[-1]
 [-1]
 [-1]]

Output of input pattern 3
[[ 1]
 [-1]
 [ 1]]

Output of input pattern 4
[[-1]
 [ 1]
 [-1]]

Testing for target patterns: Set B

Output of target pattern 1
[[1]
 [1]
 [1]
 [1]
 [1]
 [1]]

Output of target pattern 2
[[-1]
 [-1]
 [-1]
 [-1]
 [-1]
 [-1]]

Output of target pattern 3
[[ 1]
 [ 1]
 [-1]
 [-1]
 [ 1]
 [ 1]]

Output of target pattern 4
[[-1]
 [-1]
 [ 1]
 [ 1]
 [-1]
 [-1]]


In [16]:
import numpy as np

class BAM:
    def __init__(self, pattern1, pattern2):
        self.pattern1 = pattern1
        self.pattern2 = pattern2
        self.M, self.N = len(pattern1[0]), len(pattern2[0])
        self.weight_matrix = np.zeros((self.M, self.N))
        for p1, p2 in zip(pattern1, pattern2):
            self.update_weights(p1, p2)
    
    def update_weights(self, pattern1, pattern2):
        self.weight_matrix += np.outer(pattern1, pattern2)
    
    def recall(self, input_pattern):
        output = np.dot(input_pattern, self.weight_matrix)
        output[output >= 0] = 1
        output[output < 0] = -1
        return output

# Example usage:
pattern1 = np.array([[1, -1, 1], [1, 1, -1]])
pattern2 = np.array([[1, 1], [-1, 1], [1, -1]])
b = BAM(pattern1, pattern2)

print("Weight Matrix:\n", b.weight_matrix)

input_pattern = np.array([1, -1, 1])
retrieved_pattern = b.recall(input_pattern)

input_pattern_2 = np.array([1, 1, 1])  # Adjusted input pattern
retrieved_pattern_2 = b.recall(input_pattern_2)  # Retrieval with the adjusted input pattern

print("Input Pattern:", input_pattern_2)
print("Retrieved Pattern:", retrieved_pattern_2)


Weight Matrix:
 [[ 0.  2.]
 [-2.  0.]
 [ 2.  0.]]
Input Pattern: [1 1 1]
Retrieved Pattern: [1. 1.]
